### ISSUE TITLE
label support

### ISSUE THREAD

**Issue by wolftune** [andrewrk/groovebasin#207]
For anything to be the ultimate music player (and this looking good to me as a candidate), it's *gotta* be able to have multiple tags. I don't want to tag "acoustic rock" and "blues improvisation" or "acoustic blues improvisation" as genres. However the single-tag idea was created, it stinks to high heaven. Tags are not boxes, they allow more sophisticated things.

We need to be able to recognize multiple tags for any track or album or whatever. "Blues" and "Acoustic" and "improvisation" etc. all at once, and really filter by AND, OR, and NOT… so I want to tag "educational" and when I'm listening to music at a party I want to filter to NOT educational for example…

**Comment by andrewrk** [comment]
Label support progress (happening in the [labels](https://github.com/andrewrk/groovebasin/tree/labels) branch):

 * [x] - Server side support and protocol documentation for labels
 * [x] - Client: ability to add label to tracks
 * [ ] - Client: ability to delete labels
 * [ ] - Client: ability to filter library for labels
 * [ ] - Client: label dialog have check boxes for label and support adding and removing
 * [ ] - Client: filter search keyboard shortcut and gui button for popping label dialog to help complete filter search text
 * [ ] - Client: display labels in the queue

**Comment by alphapapa** [comment]
I subscribed to this issue a while back because I'm interested in GrooveBasin and in tagging/labeling my music.  I don't know if this feedback will be of any use, but I just thought I'd share what I've done with my library.

Since each player may or may not support tags/labels, and since I want to be able to switch between different players and use different software to organize my music, I have settled (so far, at least) on embedding custom tags within audio files.  I use Python and `mutagen` to write a tag with a custom name (my initials + `_Tags`) that contains a comma-separated list of labels.  I currently have it working with MP3s, Oggs, and M4A/AAC files, but it can be made to work with anything `mutagen` supports.

Then I have another Python script that goes through `~/Music` and makes an M3U playlist for each label in my custom tag.  I have this in a cron job, but it can also be run on-demand for all or certain labels.

Then I have another Python script ([plamix](https://github.com/alphapapa/plamix)) that can merge M3U playlists together.

Then I have a few small utility scripts that make it easy to quickly tag whatever track is currently playing with shell tab-completion of labels.  This works really well with Fish, because I can do something like this:
```
$ tagcurrenttrack guicla<tab>
$ tagcurrenttrack guitar/classical tal<tab>
$ tagcurrenttrack guitar/classical instrumental
```
Fish's fuzzy completion matching is really great for this.

So the end result is that my music collection is player- and organizer-independent.  All of my personal metadata is embedded in the tracks, so I don't have to transfer it from one player's database to another, etc.  And I can quickly mix playlists and pipe them directly to MPD or any other player like:
```
$ plamix classical instrumental relaxing --exclude christmas | mpd
```
I guess my conclusion is, while I'm happy to see support for tagging and labeling in GrooveBasin and other players, I don't know if I will ever use that support.  The system I have now lets me label tracks with a few keystrokes no matter what program is currently on the screen, and I can use any player.  I just can't see myself putting time and effort into building a collection of metadata that's stuck in a certain player's database.  (Of course it can be extracted or exported, but then it must also be imported elsewhere, and all of that has to be done every time one changes to a different player.)

And it also means that I can copy `~/Music` or parts of it to other systems or devices, and I can copy the M3U playlists at the same time, and use the generated playlists anywhere, even on something like an Android phone.  If I were using a player database for my labels, I'd have to install that player on whatever system I want to use in order to make use of my labels, or I'd have to manually generate and export playlists for each label using that player.

Anyway, I'm always open to new ideas and improvements, so I'm happy to hear any thoughts.  And if I can help somehow, just let me know.  :)

**Comment by andrewrk** [comment]
@alphapapa I'm envisioning a scenario where we come up with a reasonable convention for storing labels in tags (perhaps one very similar to yours but does not use your personal initials). If the convention is reasonable enough that you feel comfortable adjusting your scripts to use it, then you could continue to be free from music player lock in with your labels, while still enjoying Groove Basin's built in support for it.

**Comment by alphapapa** [comment]
That sounds great.  I would love to have player support for it.

What would be just about perfect would be if the tag name GB used for labels could be configured.  I  actually prefer to use a custom tag with my initials, because that way, if I ever add any tracks to my library, I won't have to worry about cluttering my personal labels with ones other parties have added.  

For example, I have run into this problem using Digikam and IPTC tags.  I set Digikam to read and write them from/to image files (same principle we're talking about).  And whenever I add a new image to the library, if anyone who's ever had that file before has added any tags using whatever software they use, my personal list of tags gets cluttered with theirs.  And believe me, it can become a *really* ugly mess (I am not exaggerating.  ;).

**Comment by andrewrk** [comment]
Label support is merged into master.

@alphapapa The idea we discussed is a separate issue and will be solved when Groove Basin gains ability to write tags to disk.

Saved searches, fancy metalabel stuff, and more gui for searching labels can be discussed in separate issues.

**Comment by andrewrk** [comment]
Just a little screenshot of it in action:

![](https://pbs.twimg.com/media/CQbBd08UsAAt9bD.png)

![](http://i.imgur.com/JFBUF48.png)

**Comment by alphapapa** [comment]
Nice, I like the color support.
