### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by andrewrk** [andrewrk/groovebasin#319]
This can be observed at demo.groovebasin.com.

CPU usage is low, and then when you attach the encoder, the CPU usage jumps to 100% and stays there, even when you detach the encoder or press pause.

Once the decoder is detached, the CPU usage should be very close to 0%, and even when encoding the CPU usage should be nowhere near 100%.

**Comment by andrewrk** [comment]
I think I'm close to solving this:

1. It's doing this on every server, it's just that multi-core servers the load is distributed and not blocking a single core.
2. High CPU usage goes away if you let groovebasin play with nobody streaming for 10 seconds - at that point the encoder is detached and stops spinning the CPU.

So it would appear that, instead of the encoder sleeping (waiting on a condition) when it's waiting for data, it's somehow spinning the CPU. I suspect that when this is fixed, groovebasin will take significantly less CPU usage to run even with the encoder active normally.

**Comment by redline6561** [comment]
Exciting! :)

**Comment by skarekrow** [comment]
I noticed the same symptoms. Sat at a load of about 6 before I turned streaming off and let it play for around 10 seconds. Then it stopped taking the CPU up. Very excited to see this fixed!

**Comment by Kurocon** [comment]
Can confirm that the "click play and wait 10 seconds while all streams are off" fix works to tone down the CPU usage. I am also looking forward to seeing this fixed.

**Comment by fsateler** [comment]
OK, the problem seems to be in node-groove. In particular, the buffer event is triggered continuously. modifying lib/player.js to add:

    self.grooveEncoder.on('buffer', function () { console.log(Date.now()); })

prints faster than `now()` can move forward (about 50 times per number in my pc).

Removing  the `uv_cond_signal` call in [EventAsyncCb](https://github.com/andrewrk/node-groove/blob/2.3.2/src/encoder.cc#L93-L95) fixes the problem, but it is likely to cause other problems I am not aware of.

I started snooping around node-groove. Please take everything that follows with a grain of salt as this is the first time I read node or uv code so my understanding of the APIs may be incorrect.

There seems to be an infinite loop in encoder.cc. In [AttachAsync](https://github.com/andrewrk/node-groove/blob/2.3.2/src/encoder.cc#L141) a thread is created with method `EventThreadEntry`. This method is (I guess) a loop that is meant to trigger the async callback as long as there is stuff waiting to be encoded (or already decoded?). However, this does not accomplish its purpose.

Lets start with `EventThreadEntry`. This loops as long as `groove_encoder_buffer_peek() > 0`. Inside the loop it proceeds to invoke the callback via `uv_async_send`.  Lets assume `EventAsyncCallback` then runs before `uv_async_send` returns (not really important), calls the js callback and then blocks on the context mutex because it is held by `EventThreadEntry` . Now `EventThreadEntry` can continue running, but it proceeds to block on `uv_cond_wait`. Assuming the API follows the posix cond model, then the mutex will be unlocked and `EventAsyncCallback` will be awoken, which proceeds to signal the cond immediately and releasing the mutex, thus reawakening `EventThreadEntry`. So this complex dance could be short circuited by just adding a `sleep(0)` after `uv_async_send`, since that would have the same apparent effect of yielding the cpu but still be spinning as fast as possible (ie, node-groove@b648a6279 does not accomplish fully its objective of waiting instead of spinning).

Interestingly, disabling the `EventThreadEntry` thread has the side effect of never emitting the 'buffer' event, but this seems unimportant because nothing listens to that event in groovebasin, and groovebasin continues to work using 5% cpu instead of the 150% it used to :)

**Comment by andrewrk** [comment]
wow!! @fsateler huge thanks for finding where this bug is!! I owe you big time. fix coming shortly :dancer:

**Comment by skarekrow** [comment]
Thanks @fsateler & @andrewrk! I'm looking forward to using groovebasin has this fix in.

**Comment by Kurocon** [comment]
Great job in finding the location of the bug @fsateler. I poked around the code myself but I couldn't find it.

**Comment by andrewrk** [comment]
@dwrensha this is a pretty significant fix - might be worth backporting into your sandstorm package.

**Comment by svenbit** [comment]
Will the ubuntu repository get updated with this fix? Thanks.

**Comment by andrewrk** [comment]
I think so. I'll keep this thread updated about that.
