### ISSUE TITLE
 Tried to import from Ur

### ISSUE THREAD

**Issue by tinkerp** [andrewrk/groovebasin#414]
YouTube Download import filter error, skipping: Error: status code 403
    at Request.<anonymous> (/usr/lib/nodejs/ytdl-core/lib/index.js:67:16)
    at Request.emit (events.js:95:17)
    at Request.onResponse (/usr/lib/nodejs/request/index.js:835:10)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:527:27)
Unable to import url, unrecognized format

**Comment by andrewrk** [comment]
Does it happen consistently? If so can you provide the URL?

**Comment by tinkerp** [comment]
This happens all the time, since i installed it never worked.

If i go to the import window and put this "https://www.youtube.com/watch?v=2IF5TfnmV0k" it shows that it's fetching and doesn't do nothing. When i go to the console the output is the one above.

If you need anything please say.
Thanks and good work.

**Comment by andrewrk** [comment]
Hmm. I just went to demo.groovebasin.com and pasted in that URL into the import and it worked fine. I wonder what could be different on your system. What version of groove basin are you running?

**Comment by tinkerp** [comment]
groovebasin:
  Installed: 1.4.0-1
  Candidate: 1.4.0-1
  Version table:
 *** 1.4.0-1 0
        500 http://ppa.launchpad.net/andrewrk/libgroove/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by andrewrk** [comment]
ah ok so here's the deal: You're using 1.4.0 from my PPA. It's convenient to install, but a bit out of date at the moment. Soon I'll get the PPA updated to the newest release which will have this issue fixed.

If you are impatient, you can run the latest version from source directly.

This problem happens when YouTube changes its code. When this happens, ytdl-core dependency has to figure out how to deal with the new YouTube code and then Groove Basin must be updated to the new ytdl version.

**Comment by andrewrk** [comment]
This is not actually a bug with (the master branch of) Groove Basin so I'm going to close the issue. Please open any other issues you encounter  :-)
