### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by smoebody** [andrewrk/groovebasin#431]
i repeatedly have this issue after groovebasin is up for a while (at least 24 hours)

```
node: ../nptl/pthread_mutex_lock.c:80: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
During startup program terminated with signal SIGABRT, Aborted.
(gdb) bt
No stack.
```

since i managed to get self compiled libgroove libraries and gdb up and running i thought i could provide you with a stacktrace. unfortunately - as you can see - `bt` says there is no backtrace.

any idea what causes this?

**Comment by smoebody** [comment]
i just figured that gdb mentions node has no debugging-symbols, so i installed `nodejs-dbg` (would that have been sufficient for `libgroove` as well?). maybe tomorrow i can provide a backtrace then

**Comment by andrewrk** [comment]
if it says "no stack" that might mean that the stack pointer was corrupted. If you're able to trigger the problem with valgrind, that would provide a useful backtrace. Unfortunately, it's likely difficult to trigger the problem with valgrind because it runs everything single threaded in a virtual machine, so race conditions are less likely to show up.
