### ISSUE TITLE
Fedora

### ISSUE THREAD

**Issue by marko-lazic** [andrewrk/groovebasin#452]
Hey there,
Wheres rpm package?

**Comment by marko-lazic** [comment]
https://copr.fedoraproject.org/

**Comment by norpol** [comment]
Do it, I guess? I've once tried to package groovebasin, but I discontinued because I found it boring to use archives of the source instead of using a version system (git for example). More details to [Source URL](https://fedoraproject.org/wiki/Packaging:SourceURL?rd=Packaging/SourceURL).
PS: I was using [Fedora Wiki Packaging Guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines).

**Comment by andrewrk** [comment]
I'm not going to personally package groovebasin for fedora but whoever does I'm happy to help them work out any issues they have. GitHub lets you download a source archive via a tag. For example you could use this URL to download a .tar.gz for 1.5.1: https://github.com/andrewrk/groovebasin/archive/1.5.1.tar.gz

**Comment by marko-lazic** [comment]
Thank you very much for encurage. I will look into packaging thomorow.

**Comment by norpol** [comment]
https://ttboj.wordpress.com/2015/07/23/git-archive-with-submodules-and-tar-magic/ should be also helpful :).
