### ISSUE TITLE
segfault when importing library and album art is found

### ISSUE THREAD

**Issue by sammcj** [andrewrk/groovebasin#469]
```
[mjpeg @ 0x7f6bfc4da7c0] mjpeg_decode_dc: bad vlc: 0:0 (0x7f6bfc31a7c0)
[mjpeg @ 0x7f6bfc4da7c0] error dc
[mjpeg @ 0x7f6bfc4da7c0] error y=94 x=86
[mjpeg @ 0x7f6bfc4da7c0] mjpeg: unsupported coding type (c9)
[mjpeg @ 0x7f6bfc4da7c0] mjpeg: unsupported coding type (c6)
[mjpeg @ 0x7f6bfc4da7c0] only 8 bits/component accepted
[image2 @ 0x7f6bfc4d9de0] Could not find codec parameters (Video: mjpeg)
/mnt/raid/music/somecoolband/48_13/cover.jpg: could not find codec parameters
[mjpeg @ 0x7f6c002d0ec0] Unhandled pixel format 0x11111111
[image2 @ 0x7f6c002f6e20] Could not find codec parameters (Video: mjpeg, 1500x1500)
/mnt/raid/music/somecoolband/cover.jpg: could not find codec parameters
Segmentation fault
```

**Comment by andrewrk** [comment]
In order to fix this bug, I need to be able to reproduce it. Here are a couple ways you could help me be able to reproduce it:

 * Install libgroove debug symbols, and then use gdb to get a backtrace of the segfault. This allows me to see which lines of code are related to the crash.
 * Figure out what causes the segfault (perhaps is it always this one file?) and then explain to me (perhaps send me a file) how exactly I can cause the segfault to happen on my computer.

**Comment by andrewrk** [comment]
I really would have loved to fix this, but without more details there's not much I can do.
